# -*- coding: utf-8 -*-
"""Sentiment-Analysis-IndoBERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10OtXd1oPaeIUWYx_UXIh09O5GRy7yZjR
"""

import os
import math
import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# 1) Path file
INPUT_PATH  = "BBRI_Sentiment_Final.csv"
OUTPUT_PATH = "BBRI_Sentiment_Final_IndoBERT_Full.csv"

# 2) Load data
df = pd.read_csv(INPUT_PATH)
if "Title" not in df.columns:
    raise ValueError("'Title' not found")
df["Title"] = df["Title"].astype(str).fillna("")

if torch.cuda.is_available():
    device = 0
elif hasattr(torch.backends, "mps") and torch.backends.mps.is_available():
    device = "mps"
else:
    device = -1

# 4) Load model & tokenizer
MODEL_NAME = "michaelmanurung/finbert-indonesia"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model     = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

clf = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    device=device,
    top_k=None,
    truncation=True,
    max_length=512,
)

label_map = {
    "positive": "Bullish",
    "negative": "Bearish",
    "neutral":  "Neutral",
    "Positive": "Bullish",
    "Negative": "Bearish",
    "Neutral":  "Neutral",
}


BATCH_SIZE = 64
pred_labels = []
pred_scores = []

titles = df["Title"].tolist()
n = len(titles)

for i in range(0, n, BATCH_SIZE):
    batch = titles[i:i+BATCH_SIZE]
    results = clf(batch)

    for res in results:
        best = max(res, key=lambda x: x["score"])
        raw_label = best["label"]
        mapped    = label_map.get(raw_label, raw_label)
        pred_labels.append(mapped)
        pred_scores.append(best["score"])

df["sentiment"]       = pred_labels
df["sentiment_score"] = pred_scores

df.to_csv(OUTPUT_PATH, index=False)
print(f"Done. Results save to: {OUTPUT_PATH}")
# =========================================================

print(df['sentiment'].value_counts())
print(df['sentiment'].value_counts(normalize=True)*100)

